{
  "name": "7a4026b8-6ffa-4a1f-866b-f10776b0a27c",
  "compatibilityLevel": 1601,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_9a15e8f3-df89-4c8f-9d41-783a893aae99",
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "56961707-e0b3-47f5-a0c1-12b0ada94951",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "f6a8696c-68bc-4e9d-a05b-90d6b327c2de",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "3f6ebfd6-b99a-4e6d-8dd0-2bd11e7c2b81",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "71352735-e829-4a5a-b66b-d75bdc1bbacd",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "5496b5ca-087e-411c-b0ab-670923549b61",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "3a3881ba-ed49-42b8-8674-e584d8a90fda",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "7b64a92b-7fd3-4d47-b03e-ffbd0ac63343",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "1ed53747-a72c-4218-83c7-171c2ad3ff94",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DateTableTemplate_9a15e8f3-df89-4c8f-9d41-783a893aae99",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "da5a5162-9d6f-4737-9aac-e66efd73c134",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "1d23e4d7-f43f-47e0-a140-188f1aee9631"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "9d23f4fd-40b5-44d4-8452-53c398a5c07e"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "55245c09-f3bb-4827-a4f5-5491d81d5bb9"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "092733e6-be96-44da-ada4-8a6b228eea17"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ]
      },
      {
        "name": "People",
        "lineageTag": "f6dbfdd0-3205-4c4b-a4a9-b8895d259260",
        "columns": [
          {
            "name": "Regional Manager",
            "dataType": "string",
            "sourceColumn": "Regional Manager",
            "lineageTag": "570d52b8-e5a7-4e98-b35f-4bbe5439cb09",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region",
            "lineageTag": "b3f9dfb4-9c31-4e8c-a9a1-a61c75a6e80d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "People",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Teradata.Database(\"10.200.104.44\", [HierarchicalNavigation=true]),",
                "    foodmart_bi = Source{[Schema=\"foodmart_bi\"]}[Data],",
                "    SUPERSTORE_ORDERS1 = foodmart_bi{[Name=\"SUPERSTORE_PEOPLE\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(SUPERSTORE_ORDERS1,{{\"REGIONAL_MANAGER\", \"Regional Manager\"}, {\"REGION\", \"Region\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Returns",
        "lineageTag": "7dbb9721-e18d-4342-aabb-2a302b95c6b3",
        "columns": [
          {
            "name": "Order ID",
            "dataType": "string",
            "sourceColumn": "Order ID",
            "lineageTag": "5a613367-e651-4308-ae83-0cf5c9ba7cd4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Returned",
            "dataType": "string",
            "sourceColumn": "Returned",
            "lineageTag": "f9f8c30d-3d55-49bb-b55b-3bc6461de354",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Returns",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Teradata.Database(\"10.200.104.44\", [HierarchicalNavigation=true]),",
                "    foodmart_bi = Source{[Schema=\"foodmart_bi\"]}[Data],",
                "    SUPERSTORE_ORDERS1 = foodmart_bi{[Name=\"SUPERSTORE_RETURNS\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(SUPERSTORE_ORDERS1,{{\"ORDER_ID\", \"Order ID\"}, {\"RETURNED\", \"Returned\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Calculations",
        "lineageTag": "8451f361-06da-4e23-875d-17e0f090962e",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Measure Paramt",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "Measure Paramt Order",
            "lineageTag": "1a9475ee-16e2-4227-8ebf-8c7773f25afe",
            "summarizeBy": "none",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Measure Paramt Fields"
                }
              ]
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Measure Paramt Fields",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "Measure Paramt Order",
            "lineageTag": "99d8eb2c-01ef-497e-b42a-0cdc5da7a6bc",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Measure Paramt Order",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "4ed5080c-975d-455e-a34b-896fd76c5561",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Calculations",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "    (\"Sales\", NAMEOF('Orders'[Sales]), 0),",
                "    (\"Profit\", NAMEOF('Orders'[Profit]), 1),",
                "    (\"Quantity\", NAMEOF('Orders'[Quantity]), 2)",
                "}"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Sales CY",
            "expression": [
              "SUMX(",
              "    Orders,",
              "    IF(YEAR(Orders[Order Date])='Year'[Year Value],",
              "    Orders[Sales])",
              ")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "cdd9b6e8-81d6-43de-9d37-56b51c81f724",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Orders CY",
            "expression": [
              "CALCULATE(",
              "    DISTINCTCOUNT(Orders[Order ID]),",
              "        FILTER(Orders,",
              "            YEAR(Orders[Order Date])=SELECTEDVALUE('Year'[Year])",
              "        )",
              ")        "
            ],
            "formatString": "0",
            "lineageTag": "0623e3c0-1195-4371-9713-c982991640b1"
          },
          {
            "name": "Profit CY",
            "expression": [
              "SUMX(",
              "    Orders,",
              "    IF(YEAR(Orders[Order Date])='Year'[Year Value],",
              "    Orders[Profit])",
              ")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "5fb8058d-1e14-4766-9fa8-d1eaed206259",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Orders PY",
            "expression": [
              "CALCULATE(",
              "    DISTINCTCOUNT(Orders[Order ID]),",
              "        FILTER(Orders,",
              "            YEAR(Orders[Order Date])=SELECTEDVALUE('Year'[Year])-1",
              "        )",
              ")        "
            ],
            "formatString": "0",
            "lineageTag": "c74f2607-21ac-4f24-b411-d99932bcc985"
          },
          {
            "name": "Sales PY",
            "expression": [
              "SUMX(",
              "    Orders,",
              "    IF(YEAR(Orders[Order Date])='Year'[Year Value]-1,",
              "    Orders[Sales])",
              ")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "6df97169-de89-4871-802e-a63a49725dc4",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Profit PY",
            "expression": [
              "SUMX(",
              "    Orders,",
              "    IF(YEAR(Orders[Order Date])='Year'[Year Value]-1,",
              "    Orders[Profit])",
              ")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "758a8fc5-9427-4fd8-93c9-35523c098d60",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Customers CY",
            "expression": [
              "CALCULATE(",
              "    DISTINCTCOUNT(Orders[Customer ID]),",
              "        FILTER(Orders,",
              "            YEAR(Orders[Order Date])=SELECTEDVALUE('Year'[Year])",
              "        )",
              ")        "
            ],
            "formatString": "0",
            "lineageTag": "ff34550e-e99f-4c26-aa4f-ee134ed54e0d"
          },
          {
            "name": "Dynamic Measure Calc PY",
            "expression": [
              "",
              "VAR _selectedfield= SELECTEDVALUE('Dynamic Measure Calc CY'[Choose Measure Fields])",
              "RETURN",
              "    SWITCH(",
              "        TRUE(),",
              "        _selectedfield = NAMEOF('Calculations'[Sales CY]), [Sales PY],",
              "        _selectedfield = NAMEOF('Calculations'[Profit CY]), [Profit PY],",
              "        _selectedfield = NAMEOF('Calculations'[Orders CY]), [Orders PY]",
              "    )"
            ],
            "lineageTag": "36637027-34fb-428e-a1b3-ee5dd65b043c",
            "formatStringDefinition": {
              "expression": "\"\\$#,0.00;(\\$#,0.00);\\$#,0.00\""
            }
          },
          {
            "name": "Sales % Change",
            "expression": [
              "DIVIDE(",
              "    ([Sales CY]-[Sales PY]),",
              "    [Sales PY]",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "8f8c66ba-3fae-43b3-a9cf-5c6eddcd02b1"
          },
          {
            "name": "Profit % Change",
            "expression": [
              "DIVIDE(",
              "    ([Profit CY]-[Profit PY]),",
              "    [Profit PY]",
              ")"
            ],
            "lineageTag": "52145b85-8c11-452c-bfcc-1c77c50fe4cf",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Qty % Change",
            "expression": [
              "DIVIDE(",
              "    ([Orders CY]-[Orders PY]),",
              "    [Orders PY]",
              ")"
            ],
            "lineageTag": "db13d9f8-0814-4cae-b7a2-1d297cd91dd5",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Dynamic Measure Calc % change",
            "expression": [
              "",
              "VAR _selectedfield= SELECTEDVALUE('Dynamic Measure Calc CY'[Choose Measure Fields])",
              "RETURN",
              "    SWITCH(",
              "        TRUE(),",
              "        _selectedfield = NAMEOF('Calculations'[Sales CY]), [Sales % Change],",
              "        _selectedfield = NAMEOF('Calculations'[Profit CY]), [Profit % Change],",
              "        _selectedfield = NAMEOF('Calculations'[Orders CY]), [Qty % Change]",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2a401ff7-b3a2-45c8-9849-29f61c45bd89"
          },
          {
            "name": "Customers PY",
            "expression": [
              "CALCULATE(",
              "    DISTINCTCOUNT(Orders[Customer ID]),",
              "        FILTER(Orders,",
              "            YEAR(Orders[Order Date])=SELECTEDVALUE('Year'[Year])-1",
              "        )",
              ")        "
            ],
            "formatString": "0",
            "lineageTag": "1784eb09-9232-4feb-9b2d-b8ae881536fb"
          },
          {
            "name": "Total Sales for Selected Year",
            "expression": [
              "",
              "VAR SelectedYear = SELECTEDVALUE('Year'[Year])",
              "RETURN",
              "    CALCULATE(",
              "        SUM(Orders[Sales]), -- Replace 'Sales Amount' with the measure you want to calculate",
              "        FILTER(",
              "            Orders,",
              "            YEAR(Orders[Order Date]) = SelectedYear",
              "        )",
              "    )"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "e9732616-16b4-42c3-b86b-e0dfc7893be5",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Total Profit for Selected Year",
            "expression": [
              "",
              "VAR SelectedYear = SELECTEDVALUE('Year'[Year])",
              "RETURN",
              "    CALCULATE(",
              "        SUM(Orders[Profit]), -- Replace 'Sales Amount' with the measure you want to calculate",
              "        FILTER(",
              "            Orders,",
              "            YEAR(Orders[Order Date]) = SelectedYear",
              "        )",
              "    )"
            ],
            "lineageTag": "26e1309d-908f-4551-a487-4531ca0d0da3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Orders for Selected Year",
            "expression": [
              "",
              "VAR SelectedYear = SELECTEDVALUE('Year'[Year])",
              "RETURN",
              "    CALCULATE(",
              "        DISTINCTCOUNT(Orders[Order ID]), -- Replace 'Sales Amount' with the measure you want to calculate",
              "        FILTER(",
              "            Orders,",
              "            YEAR(Orders[Order Date]) = SelectedYear",
              "        )",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "fdb0d853-e55a-4800-b17e-eb5986c7d7df"
          },
          {
            "name": "Total Customers for Selected Year",
            "expression": [
              "",
              "VAR SelectedYear = SELECTEDVALUE('Year'[Year])",
              "RETURN",
              "    CALCULATE(",
              "        DISTINCTCOUNT(Orders[Customer ID]), -- Replace 'Sales Amount' with the measure you want to calculate",
              "        FILTER(",
              "            Orders,",
              "            YEAR(Orders[Order Date]) = SelectedYear",
              "        )",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "7084a4d4-6ef0-48eb-9762-32bf8cda4561"
          },
          {
            "name": "Customer Ranks",
            "expression": [
              "RANKX(",
              "    ALLSELECTED( Orders[Customer Name]),",
              "    [Dynamic Measure Calc CY],",
              "    ,DESC",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "4ed22082-79a0-492c-a709-6448d0084136"
          },
          {
            "name": "Dynamic Measure Calc CY",
            "expression": [
              "",
              "VAR _selectedfield= SELECTEDVALUE('Dynamic Measure Calc CY'[Choose Measure Fields])",
              "RETURN",
              "    SWITCH(",
              "        TRUE(),",
              "        _selectedfield = NAMEOF('Calculations'[Sales CY]), [Sales CY],",
              "        _selectedfield = NAMEOF('Calculations'[Profit CY]), [Profit CY],",
              "        _selectedfield = NAMEOF('Calculations'[Orders CY]), [Orders CY]",
              "    )"
            ],
            "lineageTag": "d9a39a6c-fd17-48fe-8f93-240031331158",
            "formatStringDefinition": {
              "expression": "\"\""
            }
          },
          {
            "name": "Top N Customers",
            "expression": [
              "",
              "    VAR SelectedN = 'Top N'[Top N Value]",
              "    RETURN",
              "        IF([Customer Ranks] <= SelectedN,",
              "        1,",
              "        0",
              "        )"
            ],
            "formatString": "0",
            "lineageTag": "1834788a-4d87-446d-9a6f-fc4bb8109fea"
          },
          {
            "name": "Category Total Sales",
            "expression": [
              "CALCULATE(",
              "   [Total Sales for Selected Year],",
              "    ALLEXCEPT(Orders, Orders[Category])",
              ")"
            ],
            "lineageTag": "2aaaf709-eac0-41b0-9ca6-e2c56cb0b356",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Sales",
            "expression": "SUM(Orders[Sales])",
            "lineageTag": "84d7177f-a9b8-4536-ba09-75e1e5ec45c9",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Product % of Category Sales",
            "expression": [
              "DIVIDE(",
              "    [Total Sales for Selected Year],",
              "    [Category Total Sales],",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "84fd2021-a2cb-4d89-812b-ae105a2dc069"
          },
          {
            "name": "Retuned Orders CY",
            "expression": [
              "CALCULATE(",
              "    [Order Returned],",
              "        FILTER(Orders,",
              "            YEAR(Orders[Order Date])=SELECTEDVALUE('Year'[Year])",
              "        )",
              ")        "
            ],
            "formatString": "0",
            "lineageTag": "a4b139a5-f742-4a74-9282-b562e96f084b"
          },
          {
            "name": "Order Returned",
            "expression": [
              "CALCULATE(",
              "    DISTINCTCOUNT(Returns[Order ID]),",
              "    FILTER(Returns, Returns[Returned]=\"Yes\")",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "66a314ef-a9a4-45e5-b87d-700bf7f79f76"
          },
          {
            "name": "Retuned Orders PY",
            "expression": [
              "CALCULATE(",
              "    [Order Returned],",
              "        FILTER(Orders,",
              "            YEAR(Orders[Order Date])=SELECTEDVALUE('Year'[Year])-1",
              "        )",
              ")        "
            ],
            "formatString": "0",
            "lineageTag": "57c9791f-8a7f-457b-a811-6284389e212a"
          },
          {
            "name": "Total Orders returned for Selected Year",
            "expression": [
              "",
              "VAR SelectedYear = SELECTEDVALUE('Year'[Year])",
              "RETURN",
              "    CALCULATE(",
              "        [Order Returned],",
              "        FILTER(",
              "            Orders,",
              "            YEAR(Orders[Order Date]) = SelectedYear",
              "        )",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "f9a589e4-493e-45a4-bc25-8c8d4368e44a"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "cef028e4e77c4210b31425ceb3bb6d80"
          }
        ]
      },
      {
        "name": "Year",
        "lineageTag": "fd80e2c6-132d-4521-b486-5b1a1acd5b4a",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Year",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value]",
            "formatString": "0",
            "lineageTag": "045d4676-efa6-46d4-9cb2-e2b48e342a94",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 0
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Year",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "GENERATESERIES(2022, 2025, 1)"
            }
          }
        ],
        "measures": [
          {
            "name": "Year Value",
            "expression": "SELECTEDVALUE('Year'[Year], 2022)",
            "formatString": "0",
            "lineageTag": "f2a44578-5a74-4f0b-9eb9-6a6c24cde957"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "88ac0b45669749d18277ac61ffb186ea"
          }
        ]
      },
      {
        "name": "Dynamic Measure Calc CY",
        "lineageTag": "58e13420-96c8-47db-960d-7ed81f63d002",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Choose Measure",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "Choose Measure Order",
            "lineageTag": "b5ff10d8-be5f-4ff8-998f-640ca822626c",
            "summarizeBy": "none",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Choose Measure Fields"
                }
              ]
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Choose Measure Fields",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "Choose Measure Order",
            "lineageTag": "f9e6f327-2882-41e0-801d-f2b5547e245b",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Choose Measure Order",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "7de9d066-7a5d-44ad-aaf4-b06e4bf38e52",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dynamic Measure Calc CY",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "    (\"Sales\", NAMEOF('Calculations'[Sales CY]), 0),",
                "    (\"Profit\", NAMEOF('Calculations'[Profit CY]), 1),",
                "    (\"Orders\", NAMEOF('Calculations'[Orders CY]), 2)",
                "}"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "93c172d485ff41e89cd5204a3e84ee8e"
          }
        ]
      },
      {
        "name": "Top N",
        "lineageTag": "242ccf95-76ca-41ae-a239-486c82362e05",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Top N",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value]",
            "formatString": "0",
            "lineageTag": "ff07e903-bc00-40eb-b40e-d718ef35770e",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 0
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Top N",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "GENERATESERIES(0, 20, 1)"
            }
          }
        ],
        "measures": [
          {
            "name": "Top N Value",
            "expression": "SELECTEDVALUE('Top N'[Top N], 10)",
            "formatString": "0",
            "lineageTag": "b147046f-3f30-485f-9c82-3e5a8f8b0810"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "70c2d5b01319426995e1bf104d76db51"
          }
        ]
      },
      {
        "name": "Orders",
        "lineageTag": "c53a5c7e-7988-423f-b6ac-fe6d5090abb6",
        "columns": [
          {
            "name": "Row ID",
            "dataType": "int64",
            "sourceColumn": "Row ID",
            "formatString": "0",
            "lineageTag": "bce62171-929f-40f4-ae8a-b29bd2a05bd1",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Order ID",
            "dataType": "string",
            "sourceColumn": "Order ID",
            "lineageTag": "24c0e906-7deb-4708-9122-ce645d0c8d01",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Order Date",
            "dataType": "dateTime",
            "sourceColumn": "Order Date",
            "formatString": "Long Date",
            "lineageTag": "68b0b414-f318-430b-b915-8c5eee0b4170",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "b7e3f00f-8649-427f-858d-efde4ac170d5",
                "defaultHierarchy": {
                  "table": "LocalDateTable_4e42969b-3412-4d3b-be43-e9a21234c8d6",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Ship Date",
            "dataType": "dateTime",
            "sourceColumn": "Ship Date",
            "formatString": "Long Date",
            "lineageTag": "ce506276-3d1e-416e-ac69-b6087a3703a6",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "e57b5e6f-028f-438e-b59a-9476d55362e1",
                "defaultHierarchy": {
                  "table": "LocalDateTable_4ebdda87-9c4d-4890-8d7d-cb8fbe02e2fb",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Ship Mode",
            "dataType": "string",
            "sourceColumn": "Ship Mode",
            "lineageTag": "76a4e0a9-d94c-4ecd-b9a4-c99322f2b83e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Customer ID",
            "dataType": "string",
            "sourceColumn": "Customer ID",
            "lineageTag": "711e653d-0f0a-4afd-89c8-e91bff64db27",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Customer Name",
            "dataType": "string",
            "sourceColumn": "Customer Name",
            "lineageTag": "e4d06d97-bdc2-4d30-8c91-dd497aeaaa93",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Segment",
            "dataType": "string",
            "sourceColumn": "Segment",
            "lineageTag": "6efa0e90-ae06-486c-a93b-a1c4b9fd22e5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Country/Region",
            "dataType": "string",
            "sourceColumn": "Country/Region",
            "lineageTag": "a224fdfd-3c59-408e-b98e-872d0b4445f3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City",
            "lineageTag": "54c40fbd-3ebc-4fb7-8b9a-b9f81cf85580",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "State/Province",
            "dataType": "string",
            "sourceColumn": "State/Province",
            "lineageTag": "be605b2f-6d8a-441a-966d-bdfec8699dcb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Postal Code",
            "dataType": "string",
            "sourceColumn": "Postal Code",
            "lineageTag": "6ec5033b-cab6-49a9-8ddf-d027a9e3b008",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region",
            "lineageTag": "cd1d7c0c-23fa-4eee-a906-cf6c3576fb10",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product ID",
            "dataType": "string",
            "sourceColumn": "Product ID",
            "lineageTag": "1d117fb8-b1f4-492f-be4d-54637b538f1a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category",
            "lineageTag": "132e5c55-c3b2-48b9-a077-590b0a0f7dad",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sub-Category",
            "dataType": "string",
            "sourceColumn": "Sub-Category",
            "lineageTag": "ebc341ef-701b-4c25-8f4e-4d77d642b62c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product Name",
            "dataType": "string",
            "sourceColumn": "Product Name",
            "lineageTag": "648f3350-b9d5-4008-9219-2e8eedc9fb90",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sales",
            "dataType": "double",
            "sourceColumn": "Sales",
            "lineageTag": "a9a5719f-de25-4fca-8c1a-945e94ee1b73",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Quantity",
            "dataType": "int64",
            "sourceColumn": "Quantity",
            "formatString": "0",
            "lineageTag": "7579b90f-f00e-4057-98c5-f8e0605607d2",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Orders\",\"TableItemName\":\"Quantity (bins)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ]
          },
          {
            "name": "Discount",
            "dataType": "double",
            "sourceColumn": "Discount",
            "lineageTag": "c4dbdc16-fdcf-4210-b1bf-2311833b8c9a",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Profit",
            "dataType": "double",
            "sourceColumn": "Profit",
            "lineageTag": "1ccaae2e-3118-4acf-994a-fd6f082fe343",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quantity (bins)",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": [
              "IF(",
              "\tISBLANK('Orders'[Quantity]),",
              "\tBLANK(),",
              "\tINT('Orders'[Quantity] / 2) * 2",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "31c9ad13-2195-423e-a48f-4a14855374ba",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "GroupingMetadata",
                "value": {
                  "version": 0,
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "Orders"
                          }
                        },
                        "Property": "Quantity"
                      }
                    }
                  ],
                  "binningMetadata": {
                    "binSize": {
                      "value": 2.0,
                      "unit": 0
                    }
                  }
                }
              }
            ],
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"o\",\"Entity\":\"Orders\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"o\"}},\"Property\":\"Quantity\"}}],\"BinItem\":{\"Expression\":{\"Floor\":{\"Expression\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"o\"}},\"Property\":\"Quantity\"}},\"Size\":2.0}}}}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Orders",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Teradata.Database(\"10.200.104.44\", [HierarchicalNavigation=true]),",
                "    foodmart_bi = Source{[Schema=\"foodmart_bi\"]}[Data],",
                "    SUPERSTORE_ORDERS1 = foodmart_bi{[Name=\"SUPERSTORE_ORDERS\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(SUPERSTORE_ORDERS1,{{\"ROW_ID\", \"Row ID\"}, {\"ORDER_ID\", \"Order ID\"}, {\"ORDER_DATE\", \"Order Date\"}, {\"SHIP_DATE\", \"Ship Date\"}, {\"SHIP_MODE\", \"Ship Mode\"}, {\"CUSTOMER_ID\", \"Customer ID\"}, {\"CUSTOMER_NAME\", \"Customer Name\"}, {\"SEGMENT\", \"Segment\"}, {\"COUNTRY_REGION\", \"Country/Region\"}, {\"CITY\", \"City\"}, {\"STATE_PROVINCE\", \"State/Province\"}, {\"POSTAL_CODE\", \"Postal Code\"}, {\"REGION\", \"Region\"}, {\"PRODUCT_ID\", \"Product ID\"}, {\"CATEGORY\", \"Category\"}, {\"SUB_CATEGORY\", \"Sub-Category\"}, {\"PRODUCT_NAME\", \"Product Name\"}, {\"SALES\", \"Sales\"}, {\"QUANTITY\", \"Quantity\"}, {\"DISCOUNT\", \"Discount\"}, {\"PROFIT\", \"Profit\"}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns\", each [Order Date] < #date(2026, 1, 1))",
                "in #\"Filtered Rows\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "LocalDateTable_4e42969b-3412-4d3b-be43-e9a21234c8d6",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "d2960714-6181-4b03-9d34-505a33bf91d0",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "c1769ece-c29a-498e-8b6b-53595bf7a4cf",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "08eed2af-1a1c-47d3-97b9-b4257ef0248b",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "b38754aa-6a00-4bd1-9998-62829522b8dd",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "0ab96b1e-2ae0-4842-8396-2798b65a3e70",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "74b6718e-4878-4eb9-b12b-19676ad32c0c",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "4ba74f78-e7d6-42f9-8f14-a94cdcd77435",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "0225d881-a571-469a-9027-9614b35e8b63",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_4e42969b-3412-4d3b-be43-e9a21234c8d6",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Orders'[Order Date])), 1, 1), Date(Year(MAX('Orders'[Order Date])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "5a2c19f8-56b6-48eb-8003-49619dd1e7df",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "963b28c2-5458-48e1-95e3-3246b45d1d10"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "725b0e56-bc70-4191-9062-204edc07ed44"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "f9de2949-bc6d-4a6e-8a64-5dc90bc7917d"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "2cb56ece-62ef-44f5-b969-1e95688c7aa4"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "LocalDateTable_4ebdda87-9c4d-4890-8d7d-cb8fbe02e2fb",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "1281df09-f886-4e64-8b8e-51cc35175829",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "c806275c-35ee-494e-9392-ec3372a68b0e",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "9e21b240-ff0a-4972-afe1-4f24a8c30bdf",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "dc8eb592-ea69-4bd5-aadd-975e32d89381",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "367945be-5abe-45e3-aea2-6fb82524719e",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "ef456c09-f9a1-4b2a-b6cb-9fb18aa03bdf",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "902286a9-1d07-4f89-9baa-cd02f7b8272c",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "3db0f3d5-3891-4698-a399-13cec78d4ef5",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_4ebdda87-9c4d-4890-8d7d-cb8fbe02e2fb",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Orders'[Ship Date])), 1, 1), Date(Year(MAX('Orders'[Ship Date])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "5be935e7-a47b-40a7-ac9b-0571ef9bfd5e",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "e2a5a045-c09e-4a0b-aed4-1abe1445f6a2"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "c3692271-bb64-48bd-9c7b-a0e09d9feb88"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "e18c44ba-8560-4aa3-884c-6fa958406615"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "8e59eb30-b86c-472f-82a8-2b940690f514"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "b7e3f00f-8649-427f-858d-efde4ac170d5",
        "fromTable": "Orders",
        "fromColumn": "Order Date",
        "toTable": "LocalDateTable_4e42969b-3412-4d3b-be43-e9a21234c8d6",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "e57b5e6f-028f-438e-b59a-9476d55362e1",
        "fromTable": "Orders",
        "fromColumn": "Ship Date",
        "toTable": "LocalDateTable_4ebdda87-9c4d-4890-8d7d-cb8fbe02e2fb",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "AutoDetected_026a7ace-afef-4941-831b-c60131ff64b7",
        "fromTable": "Orders",
        "fromColumn": "Region",
        "toTable": "People",
        "toColumn": "Region",
        "isActive": false
      },
      {
        "name": "84dcade2-d371-40fb-4e85-35e2a32f604a",
        "fromTable": "Orders",
        "fromColumn": "Order ID",
        "toTable": "Returns",
        "toColumn": "Order ID"
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "roles": [
      {
        "name": "All",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Orders",
            "filterExpression": "TRUE()"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "c2df540e851a431e83e0667f79da78e2"
          }
        ]
      },
      {
        "name": "Central South Region",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Orders",
            "filterExpression": "[Region] = \"Central\" || [Region] = \"South\""
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "61eb10a0dd00424db809060a6d1949f7"
          }
        ]
      },
      {
        "name": "East Region",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Orders",
            "filterExpression": "[Region] == \"East\""
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "5e276ab984e847e799536da41065fbe5"
          }
        ]
      },
      {
        "name": "West Region",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Orders",
            "filterExpression": "[Region] == \"West\""
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b3d94951c8fb496cbcd9e032b76edfff"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"People\",\"Returns\",\"Orders\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.145.1262.0 (25.07)+10bdeda5ab0db954b2cf824e7a117ad7cee97f88"
      }
    ]
  }
}
